services:

  mongo-db:
    image: mongo:latest
    container_name: mongoDB
    ports:
      - 27017:27017
    environment: 
      MONGO_INITDB_ROOT_USERNAME: mongoadmin 
      MONGO_INITDB_ROOT_PASSWORD: mongopasswd  
    volumes: 
      - type: bind
        source: ./mongo-entrypoint
        target: /docker-entrypoint-initdb.d/
    healthcheck: 
      test: echo 'db.runCommand({find:"fitbot_db.fitbotUser"}).ok' | mongosh --authenticationDatabase admin --host localhost -u mongoadmin -p mongopasswd admin --quiet | grep -q 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s


volumes:
  mymongodata: